### ISSUE TITLE
AppCenter Review: Please rename

### ISSUE THREAD

**Issue by danirabbit** [gandalfn/pantheon-sound-control#14]
After some discussion with other reviewers, we've decided to mark this release as "Needs Fixing" due to the use of "Pantheon" in the name. This naming makes it sound like this is a product of elementary instead of a third party app. We've updated our [Publishing guidelines](https://github.com/elementary/houston/wiki/Before-You-Publish) with this new requirement.

**Comment by gandalfn** [comment]
Ok, thanks for the feedback, it makes sense.

I do not have much imagination for application names. I will try to dig my head to find another name :-)

It does not really have link with this app, but you know I also maintain a repository of elementary packages under debian. I named it pantheon-debian if that's a problem tell me I'll change its name as well.

**Comment by gandalfn** [comment]
Renamed to suka hottoe ("sound control" in minion language http://funtranslations.com/minion ) :satisfied:
